def main():
	P = int( input( "\nEnter the prime number P : " ) )
	G = int( input( "Enter the primitive root of P : " ) )

	a = int( input( "\nEnter the private key a : " ) )
	b = int( input( "Enter the private key b : " ) )

	x = pow( G, a, P )
	y = pow( G, b, P )

	print( "\nKey generated by Alice =", x )
	print( "Key generated by Bob =", y )

	ka = pow( y, a, P )
	kb = pow( x, b, P )

	print( "\nSecret key generated by Alice =", ka )
	print( "Secret key generated by Bob =", kb )

main()